/**
 * The data definitions: how the shop's information is represented.
 * Every function in the domain takes and returns these; docs/DESIGN.md
 * explains the choices.
 */
import type { Cents } from './money';
import type { Instant } from './time';

/** Id: a record's identity, generated by the domain (a UUID). */
export type Id = string;

// ---- Catalogue --------------------------------------------------------------

export const GARMENTS = ['oversized_200g', 'regular_fit'] as const;
/** Garment: a kind of blank shirt the shop buys. */
export type Garment = (typeof GARMENTS)[number];

export const COLORS = ['black', 'white'] as const;
/** Color: a shirt colour. */
export type Color = (typeof COLORS)[number];

export const SIZES = ['XS', 'S', 'M', 'L', 'XL', 'XXL'] as const;
export type Size = (typeof SIZES)[number];

/** Sku: one kind of blank shirt, e.g. an oversized black M. */
export type Sku = { garment: Garment; color: Color; size: Size };

/** Design: an artwork, e.g. "UÇK". */
export type Design = { id: Id; name: string; notes: string; archived: boolean; createdAt: Instant };

/**
 * Print: the DTF version of a design for one shirt colour — the artwork
 * differs between black and white shirts. perSheet is how many shirts' worth
 * (front + back) fit on one 56 × 100 cm sheet; front and back are pictures.
 */
export type Print = {
	id: Id;
	designId: Id;
	shirtColor: Color;
	perSheet: number;
	front: Id | null;
	back: Id | null;
};

export const IMAGE_MIMES = ['image/webp', 'image/jpeg', 'image/png'] as const;
export type ImageMime = (typeof IMAGE_MIMES)[number];
/** Upload: a picture as it arrives, before it is stored: base64 data. */
export type Upload = { mime: ImageMime; data: string };
/** Image: a stored picture (a print's artwork, or a custom order's mockup). */
export type Image = Upload & { id: Id; createdAt: Instant };

// ---- Customers --------------------------------------------------------------

export const COUNTRIES = ['XK', 'AL', 'MK', 'OTHER'] as const;
export type Country = (typeof COUNTRIES)[number];

/** Customer: someone who orders. Known by their phone number. */
export type Customer = {
	id: Id;
	name: string;
	phone: string;
	address: string;
	city: string;
	country: Country;
};

// ---- Orders -----------------------------------------------------------------

export const ORDER_KINDS = ['sale', 'gift'] as const;
/** sale: sold. gift: sent free to an influencer, a marketing cost. */
export type OrderKind = (typeof ORDER_KINDS)[number];

export const CHANNELS = ['instagram', 'messenger', 'tiktok', 'whatsapp', 'direct', 'other'] as const;
/** Channel: where the order came from. */
export type Channel = (typeof CHANNELS)[number];

export const DELIVERY_METHODS = ['courier', 'hand'] as const;
export type DeliveryMethod = (typeof DELIVERY_METHODS)[number];

/**
 * Delivery: how the order reaches the customer, and what that costs the SHOP.
 *   courier: through the post; trackingRef is the courier's parcel number
 *   hand:    handed over in person
 */
export type Delivery =
	| { method: 'courier'; cost: Cents; trackingRef: string }
	| { method: 'hand'; cost: Cents };

/**
 * Artwork: what is printed on a line's shirts.
 *   none:   a plain shirt
 *   print:  a design from the catalogue
 *   custom: personalised for this order, with its own DTF; front and back are
 *           the mockups, which a custom line can't exist without.
 *           printReady: its DTF has come back from the printer.
 */
export type Artwork =
	| { kind: 'none' }
	| { kind: 'print'; printId: Id }
	| { kind: 'custom'; front: Id; back: Id; printReady: boolean };

/**
 * LineCost: what one shirt of a line costs, snapshotted when the order is
 * taken, so a later price change never rewrites past profit.
 */
export type LineCost = { blank: Cents; dtf: Cents; labor: Cents };

export type OrderLine = {
	id: Id;
	sku: Sku;
	artwork: Artwork;
	quantity: number; // ≥ 1
	unitPrice: Cents; // what the customer pays per shirt; 0 on gifts
	cost: LineCost;
};

export const STATUSES = [
	'new',
	'in_production',
	'ready',
	'with_courier',
	'delivered',
	'returned',
	'cancelled'
] as const;
/**
 * Status: where an order is in the process.
 *   new → in_production → ready (made and packed) → with_courier → delivered
 *   returned: the courier brought it back.   cancelled: it won't happen.
 * Hand deliveries go from ready straight to delivered.
 */
export type Status = (typeof STATUSES)[number];

export const EVENTS = ['start', 'make', 'hand_over', 'deliver', 'return', 'cancel', 'undo'] as const;
/** Event: something that happens to an order and moves it along. */
export type OrderEvent = (typeof EVENTS)[number];

export type Order = {
	id: Id;
	code: string; // "HS-0042", what people say out loud
	customerId: Id;
	kind: OrderKind;
	channel: Channel;
	delivery: Delivery;
	lines: OrderLine[]; // at least one
	packaging: Cents;
	shippingCharged: Cents; // what the customer pays for shipping; usually 0
	discount: Cents;
	notes: string;
	status: Status;
	/**
	 * Whether making it takes stock from the ledger. False for orders made
	 * before the app kept stock: their shirts were never on its shelves.
	 */
	stockTracked: boolean;
	isDemo: boolean;
	createdAt: Instant;
	madeAt: Instant | null;
	handedOverAt: Instant | null;
	deliveredAt: Instant | null;
	returnedAt: Instant | null;
	cancelledAt: Instant | null;
};

// ---- Payments ---------------------------------------------------------------

export const PAYMENT_METHODS = ['cod', 'bank', 'cash'] as const;
/** cod: cash on delivery, paid out by the courier. bank: transfer. cash: in hand. */
export type PaymentMethod = (typeof PAYMENT_METHODS)[number];

/** Payment: money received for an order. */
export type Payment = { id: Id; orderId: Id; amount: Cents; method: PaymentMethod; receivedAt: Instant };

// ---- Stock ------------------------------------------------------------------

/** Subject: something the shop keeps on the shelf. */
export type Subject = { kind: 'blank'; sku: Sku } | { kind: 'print'; printId: Id };

export const MOVEMENT_REASONS = ['opening', 'purchase', 'made', 'unmade', 'adjustment'] as const;
/**
 * opening: what was there when the ledger started.   purchase: bought.
 * made: used to make an order.   unmade: given back when making was undone.
 * adjustment: a correction, a count, a spoiled shirt.
 */
export type MovementReason = (typeof MOVEMENT_REASONS)[number];

/**
 * Movement: one change to what's on the shelf. What's there now is the sum
 * of a subject's movements; no count is stored that could drift from them.
 */
export type Movement = {
	id: Id;
	subject: Subject;
	delta: number; // never 0
	reason: MovementReason;
	note: string;
	orderId: Id | null;
	purchaseId: Id | null;
	at: Instant;
};

// ---- Purchases (money out) --------------------------------------------------

export const EXPENSE_CATEGORIES = ['packaging', 'marketing', 'other'] as const;
export type ExpenseCategory = (typeof EXPENSE_CATEGORIES)[number];

export type BlankLine = { sku: Sku; quantity: number; unitCost: Cents };
export type PrintLine = { printId: Id; quantity: number };

/**
 * Purchase: money the shop spent.
 *   blanks:  blank shirts, which go on the shelf
 *   dtf:     DTF sheets; the prints they carry go on the shelf
 *   expense: anything else
 */
export type Purchase = { id: Id; date: Instant; note: string; isDemo: boolean } & (
	| { kind: 'blanks'; lines: BlankLine[] }
	| { kind: 'dtf'; sheets: number; sheetPrice: Cents; lines: PrintLine[] }
	| { kind: 'expense'; category: ExpenseCategory; amount: Cents }
);

// ---- Settings ---------------------------------------------------------------

/** Settings: the prices that decide what a new order costs. */
export type Settings = {
	defaultPrice: Cents; // pre-filled price per shirt
	sheetPrice: Cents; // one 56 × 100 cm DTF sheet
	customPerSheet: number; // personalised prints (front + back) on one sheet
	laborPerShirt: Cents; // pressing, folding and packing one shirt
	packagingPerOrder: Cents; // bag or mailer, per parcel
	blankCost: Record<Garment, Cents>; // until blanks are bought through the app
	courierCost: Record<Country, Cents>; // what the courier charges the shop
};

export const DEFAULT_SETTINGS: Settings = {
	defaultPrice: 2500,
	sheetPrice: 1200,
	customPerSheet: 4,
	laborPerShirt: 200,
	packagingPerOrder: 12,
	blankCost: { oversized_200g: 800, regular_fit: 800 },
	courierCost: { XK: 250, AL: 500, MK: 500, OTHER: 500 }
};

// ---- The world and changes to it -------------------------------------------

/** World: everything the shop knows, as one value. Pictures' data aside. */
export type World = {
	settings: Settings;
	designs: Design[];
	prints: Print[];
	customers: Customer[];
	orders: Order[];
	payments: Payment[];
	purchases: Purchase[];
	movements: Movement[];
};

/**
 * Change: one thing to write. A command decides a list of them; the shell
 * writes the list in one transaction.
 *   put:    create or replace the whole record (an order with its lines,
 *           a purchase with its lines)
 *   delete: remove the record (with its lines)
 */
export type Change =
	| { put: 'customer'; value: Customer }
	| { put: 'design'; value: Design }
	| { put: 'print'; value: Print }
	| { put: 'image'; value: Image }
	| { put: 'order'; value: Order }
	| { put: 'payment'; value: Payment }
	| { put: 'purchase'; value: Purchase }
	| { put: 'movement'; value: Movement }
	| { put: 'settings'; value: Settings }
	| { delete: 'order' | 'payment' | 'purchase' | 'movement' | 'image' | 'design' | 'print'; id: Id };

/** Context: what a command needs from outside — the time, and fresh ids. */
export type Context = { now: Instant; newId: () => Id };

export const emptyWorld = (): World => ({
	settings: structuredClone(DEFAULT_SETTINGS),
	designs: [],
	prints: [],
	customers: [],
	orders: [],
	payments: [],
	purchases: [],
	movements: []
});
